config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: "users/sessions", passwords: "users/passwords" }, :path => "members" do
    get '/members/sign_out' => 'users/sessions#destroy'
  end
  root to: 'main#index'
  patch "update-subscription" => 'main#convert_user'
  get "register" => 'main#register'
  post "contact-us" => 'main#contact_us'
  get "dashboard" => 'admin#index'
  post "availability_restaurant" => 'main#restaurant'
  post "availability_customer" => 'main#customer'
  post "get_authenticity_token" => 'main#get_token'
  get "reservations" => 'main#reservations'
  get "restaurant/:slug" => 'main#restaurant'
  scope :dashboard do
    get "settings" => 'admin#settings'
    patch "settings/save" => 'admin#settings_save'
    patch "settings/logo" => 'admin#remove_logo'
    patch '/reservations/success/:reservation_code' => 'reservations#success'
    delete '/reservations/destroy_customer/:reservation_code' => 'reservations#destroy_customer'
    get 'restrictions/:id' => 'restrictions#index'
    post 'restrictions/create'
    delete 'restrictions/destroy/:id' => 'restrictions#destroy'
    resources :pages,:param => :slug do
      member do
          patch 'remove_image'
      end
    end
    resources :posts,:param => :slug do
      member do
          patch 'remove_image'
      end
    end
    resources :restaurants , :param => :slug do
      member do
        patch 'remove_image'
        
      end
      collection do 

        get 'list' 
      end
      resources :tables do
        
        
      end
      resources :details ,:controller => :branches , :param => :slug do
        member do
          patch 'remove_image'
        end
        collection do 
          get 'list' 
        end
        
      end
    end
    resources :reservations,:param => :reservation_code do
      collection do 
        get "list/:id" => 'reservations#list'
        post "filtered_list"
      end

    end
    resources :customers, :controller =>"users" , :param => :membership do
      collection do 
        post "filtered"
        get "filtered"
      end
    end
   
     
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	
	#relations
	has_many :branches , dependent: :destroy
	has_many :tables , dependent: :destroy
	has_many :date_restrictions , dependent: :destroy
	belongs_to :user 
	#scopes
	scope :by_user, lambda { |user| where("restaurants.user_id = ?",user) }
	scope :published, lambda { where("restaurants.status = ?",true) }
	#validations
	validates :title,		:presence => true,
							:length => { :maximum => 25 }

	validates :slug, 		:uniqueness => true,
							:presence => true
					
	validates :user_id, :presence => true,:numericality => { :only_integer => true , :greater_than => 0 }		
	# This method associates the attribute ":avatar" with a file attachment
	  has_attached_file :logo, styles: {
	    thumb: '100x100>',
	    square: '200x200#',
	    medium: '300x300>'
	  }

	  # Validate the attached image is image/jpg, image/png, etc
	  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/
		
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :auth_user , :except => [:list]
  layout 'admin'
  authorize_resource :class => false
 def index
    if current_user.role_id != 1
      @restaurants = Restaurant.where(["user_id = ?",current_user.id])
    else
      @restaurants = Restaurant.all
    end
  	
  end
def list
    render json: Restaurant.published
end
  def edit
    if current_user.role_id == 1
      @restaurant = Restaurant.where(["slug = ?",params[:slug]]).first
     
      @users = User.where(["role_id = ?",2])

        
    else
       @restaurant = Restaurant.where(["slug = ? AND user_id = ?",params[:slug],current_user.id]).first
    end
    if !flash[:model].blank?
        @restaurant.assign_attributes(flash[:model])
    end
  end

  def new
    @restaurant = Restaurant.new
    if current_user.role_id == 1
        @users = User.where(["role_id = ?",2])

        
      end
    if !flash[:model].blank?
        @restaurant.assign_attributes(flash[:model])
    end
  end
  
  def create
    @restaurant = Restaurant.new(restaurant_params("test"))
    
    if @restaurant.save
      flash[:notice] = "Restaurant saved, Kindly Enter the details for the restaurant to appear on frontpage"

      redirect_to(new_restaurant_detail_path(@restaurant.slug))
    else
      
      flash[:model] =@restaurant
      flash[:error_model] =@restaurant.errors.full_messages
     
      redirect_to(:action=>'new')
    end

  end

  def destroy
    if current_user.role_id != 1
      restaurant = Restaurant.where(["slug = ? AND user_id = ?",params[:slug],current_user.id]).first
    else
      restaurant = Restaurant.where(["slug = ?",params[:slug]]).first
    end
   
    
    
    restaurant.destroy
    render json: { "gst" => "deleted" }
  end

  def remove_image
  	if current_user.role_id != 1
      restaurant = Restaurant.where(["slug = ? AND user_id = ?",params[:slug],current_user.id]).first
    else
      restaurant = Restaurant.where(["slug = ?",params[:slug]]).first
    end
    
    restaurant.logo.destroy
    restaurant.logo.clear
    restaurant.logo = nil
    restaurant.save
    render json: { "gst" => "deleted" } 
  end

  def update
    if current_user.role_id != 1
      @restaurant = Restaurant.where(["slug = ? AND user_id = ?",params[:slug],current_user.id]).first
    else
      @restaurant = Restaurant.where(["slug = ?",params[:slug]]).first
    end
    if @restaurant.update_attributes(restaurant_params(@restaurant.featured_image))
      flash[:notice] = "Restaurant saved"
      redirect_to(edit_restaurant_detail_path(@restaurant.slug,@restaurant.branches[0].slug))
    else
      flash[:model] =@restaurant
      flash[:error_model] =@restaurant.errors.full_messages
     
      redirect_to(:action=>'edit')
      
    end
  end

  private
  def restaurant_params(old_image)
    if old_image.blank?
      old_image = "test"
    end
    
    if params[:restaurant][:slug].blank?
       params[:restaurant][:slug] = (current_user.membership+" "+params[:restaurant][:title]).parameterize
    else
        params[:restaurant][:slug] = params[:restaurant][:slug].parameterize
    end
    if current_user.role_id == 2
      params[:restaurant][:user_id] = current_user.id 
    end
    params.require(:restaurant).permit(:title,:slug,:status,:description,:featured_image,:user_id,:logo)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
  <div class="form-group">
            <div class="col-md-6 ">
              <%= f.text_field(:title,:class => 'form-control' , :placeholder =>"Title")%>
            </div>
            <div class="col-md-6 ">
              <%= f.text_field(:slug , :class => 'form-control' , :placeholder =>"Slug")%>
            </div>
          </div>
          <div class="form-group">
             <div class="col-md-6 ">
              <%= f.select(:status, options_for_select([['Published',1],['Unpublished',0]],(@restaurant.status ? 1 : 0)),{},{ :class=>"form-control"}) %>
            </div>
            <div class="col-md-6 ">
              <%= f.file_field(:logo , :class => 'form-control' , :placeholder =>"Logo") %>
            </div> 
          </div>
          <% if current_user.role.role == "admin" %>
          <div class="form-group">
            <div class="col-md-6 ">
              <%= f.select(:user_id, options_from_collection_for_select(@users,"id","name",@restaurant.user_id), {:include_blank => 'Select User'},{ :class=>"form-control"}) %>
            </div>
          </div>
          <%   end %>
          <div class="form-group">
            <div class="col-md-8 ">
              <%= f.text_area(:description, :size => '40x6' , :class => 'form-control' , :placeholder =>"Description") %>
            </div>
           
          </div>

app/views/restaurants/edit.html.erb
<style>
.form-yellow {
   margin-top: 0;
}
</style>

<div class="container-fluid content table-content">
      <div class="breadcrumb">reserva de edición<% if user_signed_in? %>
      <strong> | <%= current_user.name %></strong>
      <% end %></div>
      <div class="row table-yellow form-yellow">
        <div class="col-md-2 col-md-push-10">
          
          <img src="<%= @restaurant.logo.url %>" class="img-responsive img-circle" id="featured_image" >
                      
        
        </div>
        <%= form_for(:restaurant, :url=>{:action => 'update', :slug => @restaurant.slug},:method=>"put",:multipart=>true, :html => {:class=>"form-horizontal col-md-10  col-md-pull-2"}) do |f| %>
        <%= render(:partial => "form",:locals=>{:f=>f})%>
        <div class="form-group">
            <div class="col-md-6">
             	<button type="submit" class="form-control" >Edit Restaurant</button>
            </div>
            <div class="col-md-6">
            	<input type="button" class="form-control" onclick="$('.remove_image').click();" value="Remove Restaurant Logo">
             	 <%= link_to 'Remove Featured Image' , {:action => 'remove_image' , :slug => @restaurant.slug}, method: :patch, data: { confirm: 'Are you sure?' }, :remote => true, "data-type" => :json , :class => 'remove_image',:style=>"display:none" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

app/views/restaurants/index.html.erb
<div class="container-fluid content table-content">

<div class="breadcrumb">restaurantes<% if user_signed_in? %>
      <strong> | <%= current_user.name %></strong>
      <% end %><strong> | <%= link_to("Add Restaurant",{:action=>'new'},:class=>'action restaurant new' , :style => "") %>
</strong></div>
      <div class="row table-yellow">
<table class="table table-striped" summary="Restaurant list">
  <tr class="header">
    <th>&nbsp;</th>
    <th>Title</th>
    <th>Status</th>
    <th>Actions</th>
  </tr>
  <% @restaurants.each_with_index do |d,i| %>
  <tr class="">
    <td class="position"><%= i+1 %></td>
    <td><%= d.title %></td>
    <td><%= d.status ? "Published" : "Unpublished" %></td>
    <td class="actions">
        <% if d.branches.count > 0 %>
     	  <%= link_to("Informacion", edit_restaurant_detail_path(d.slug,d.branches[0].slug), :class => 'action branches', :style => "color:black") %> 
        <% else %>
         <%= link_to("Informacion", new_restaurant_detail_path(d.slug), :class => 'action branches', :style => "color:black") %> 
         <% end %>
        |
      	<%= link_to("Editar", {:action => 'edit', :slug => d.slug}, :class => 'action edit' , :style => "color:black") %> |
      	<%= link_to 'Borrar' , {:action => 'destroy' , :slug => d.slug}, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, "data-type" => :json , :class => 'delete_row' , :style => "color:black" %> |
        <% if !d.branches[0].blank? %>
        <%= link_to 'Reservaciones' , {:controller => :reservations ,:action => 'list' , :id => d.branches[0].id}, :style => "color:black" %> |
        <% end %>
        <%= link_to 'Mesas' , restaurant_tables_path(d.slug), :style => "color:black" %> | 
        <%= link_to 'Restricciones De Fecha' , {:action=> :index,:controller=>:restrictions,:id=>d.id}, :style => "color:black" %>
    </td>
  </tr>
  <% end %>
  
</table>
</div>
</div>

</div>

app/views/restaurants/new.html.erb
<style>
.form-yellow {
   margin-top: 0;
}
</style>

<div class="container-fluid content table-content">
      <div class="breadcrumb">nueva reserva<% if user_signed_in? %>
      <strong> | <%= current_user.name %></strong>
      <% end %></div>
      <div class="row table-yellow form-yellow">
        
        <%= form_for(:restaurant, :url=>{:action=>'create'},:multipart=>true, :html => {:class=>"form-horizontal col-md-10 "}) do |f| %>
       		<%= render(:partial => "form",:locals=>{:f=>f})%>
          
          <div class="form-group">
            <div class="col-xs-offset-2 col-xs-8">
             	<%= submit_tag("Create Restaurant",:class=>"form-control")%>
            </div>
          </div>
        <% end %>
      </div>
    </div>